
[ClassVersion("1.0.0.0"), FriendlyName("xVSTSAgent")]
class xVSTSAgent : OMI_BaseResource
{
    [Key] String Name;
    [Write] String Pool;
    [Required, EmbeddedInstance("MSFT_Credential")] String AccountCredential;
    [Required] String Account;
    [Write, EmbeddedInstance("MSFT_Credential")] String LogonCredential;
    [Required] String AgentDirectory;
    [Write] Boolean PrefixComputerName;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

